NAMES = [
    "Prosecco & Strawberry",
    "Caramel Cream",
    "Peanut",
    "Fudge Cheesecake",
    "Butterscotch Waitrose",
    "Boysenberry",
    "Caramel Cheesecake",
    "Chocolate Poppers",
    "Coca Cola (Coke)",
    "Candied Bacon",
    "Sweet Corn",
    "Black Raspberry",
    "Bourbon",
    "Grape",
    "Almond, Chocolate, Fudge & Raspberry",
    "Banana Oreo",
    "Red Bean",
    "Candy Canes",
    "Banana Cream Pie",
    "Italian Cherry",
    "Chocolate & Guiness",
    "Dark Chocolate",
    "Chocolate, Chocolate & Peanut Butter",
    "Milk Chocolate Black Pepper",
    "Gin",
    "Chocolate Pecan",
    "Marshmallow & Peanut Butter",
    "Lemonade",
    "Tiramisu",
    "Banana Walnut",
    "Caramel Cashew",
    "Chocolate Cookies & Cream",
    "Pistachio Pistachio (Double Pistachio)",
    "Coffee",
    "Cherry, Chocolate & Vanilla",
    "Gin & Kaffir Lime",
    "Violet",
    "Almond, Caramel, Chocolate, Cookie & Vanilla",
    "Caramel & Malted Vanilla",
    "Fried Ice Cream",
    "Coconut",
    "Dondurma",
    "Orange",
    "Cake Batter",
    "Mojito",
    "Amaretto Chocolate",
    "Banana, Chilli Jelly, Rum & Chocolate",
    "Vietnamese Coffee",
    "Caramel, Chocolate Cheesecake & Pecans",
    "Chocolate Fudge & Orange",
    "Marshmallow",
    "Chocolate Coconut Candy Bar",
    "Christmas Spaghetti",
    "Caramel, Marshmallow & Peanut Butter",
    "Coconut Fudge",
    "Kahlua, Vodka & Irish Creme Liqueur",
    "Asparagus",
    "Walnut",
    "Apple, Caramel Toffee",
    "Banana Split",
    "Brown Sugar, Coriander & Lime",
    "Caramel, Pecans & Vanilla",
    "Chocolate Mint & Oreo",
    "Goat Cheese, Honey, Pistachio",
    "Nutella",
    "Lemon Meringue",
    "Snickers",
    "Butter Brickle",
    "Chocolate Speed Bumps",
    "Chocolate Turtle",
    "Brown Sugar",
    "Rainbow",
    "Banana, Fudge & Walnuts (aka Chunky Monkey)",
    "Bourbon Cherry Cobbler",
    "Cherokee Gold",
    "Almond",
    "Brown Bread",
    "White Russian",
    "Black Walnut Cheesecake",
    "Cookie & Mint",
    "Ginger, Honey & Lemon",
    "Lemon Cookie",
    "Saffron",
    "Anzac Biccuit",
    "Almond, Chocolate Chocolate (Almond Double Chocolate)",
    "Bacon & Bourbon",
    "Caramel & Twix",
    "Coffee Molasses",
    "Cookie Dough",
    "Galaxy",
    "Jager bomb",
    "Marshmallow Pound Cake",
    "Caramel, Chocolate, Oatmeal Cookies, Sweet Cream & Walnuts",
    "Chocolate Krispies, Peanut Butter & Vanilla",
    "Fudge Chocolate",
    "Saffron Pistachio",
    "Durian",
    "Pear",
    "Red Velvet Cake Batter",
    "Tutti Frutti",
    "Almond & Pistachio",
    "Almond, Honey, Pecan, Pistachio & Salt",
    "Brownie Snicker Finger",
    "Caramallow Chocolate",
    "Cherry & Vanilla",
    "Dark Chocolate, Marshmallow, Cookies & Brownies",
    "Teaberry",
    "Halva",
    "Salted Caramel",
    "Banana Nut Bread",
    "Bourbon Brown Sugar",
    "Caramel Brownie & Vanilla",
    "Caramel, S’mores & Peanut Butter",
    "Chocolate Peppermint",
    "Ginger & White Chocolate",
    "Unicorn",
    "Egg nog",
    "Strawberry Cheesecake",
    "Chocolate Malted Milk",
    "Cookies & Strawberries",
    "Raisin & Rum",
    "Espresso",
    "Pecan",
    "Pineapple",
    "Banana Fudge",
    "Caramel & Caramel",
    "Chocolate Cherry Fudge",
    "Cream & Strawberries",
    "Gingersnap & Pumpkin",
    "Pecan & Pumpkin",
    "Bittersweet Chocolate",
    "Olive Oil",
    "Passionfruit",
    "Sherbet",
    "Blueberry Cobbler",
    "Blueberry Pie",
    "Coffee Cake Streusel",
    "Almond Butter Fudge",
    "Almond, Toffee & Whiskey",
    "Apple & Guava",
    "Apple Caramel",
    "Bailey’s & Toffee",
    "Black Raspberry Oreo",
    "Caramel Peanut Butter",
    "Caramel Praline",
    "Chilli Chocolate",
    "Chocolate Espresso",
    "Chocolate Mint Toffee",
    "Lemonade & Raspberry",
    "Pecan & Scotch",
    "Salty Plum",
    "Cacao Nib",
    "Banana Pudding",
    "Chocolate Lava Cake",
    "Jelly & Peanut Butter",
    "Old Fashioned",
    "Pumpkin Pie",
    "Almond Toffee",
    "Almond, Amaretto & Chocolate",
    "Banana Chocolate Chip",
    "Blue Cheese & Pear",
    "Blueberry French Toast",
    "Caramel, Chocolate & Coffee",
    "Chocolate, Creme de Menthe & Cookie",
    "Chocolate, Peanut Butter & Vanilla",
    "Coconut & Nuts",
    "Maple",
    "Red Wine",
    "Buttercake",
    "Chocolate Cake Batter",
    "Chocolate Cheesecake",
    "Fairy Bread",
    "Ice Box Cake",
    "Peanut Butter Cups",
    "Superman",
    "White Almond Fudge",
    "Bacon, Cocoa Nibs & Sweet Corn",
    "Banana French Toast",
    "Caramel, Chocolate & Fudge",
    "Chocolate & Vanilla",
    "Chocolate, Vanilla & Chocolate Chip Cookie Dough",
    "Coffee Mocha",
    "Cream & Peaches",
    "Maple Pecan",
    "Maple, Pecan & Sweet Potato",
    "Orange & Poppyseed",
    "Raspberry & Sherbet",
    "Sweet Cream",
    "Banana",
    "Cheddar",
    "Garlic",
    "Gingerbread",
    "Jelly Bean",
    "Mocha",
    "Rice",
    "Cinnamon Toast (aka French Toast)",
    "Kulfi",
    "Peach Cobbler",
    "Spumoni",
    "Almond & Vanilla",
    "Banana Peanut Butter Ripple",
    "Bananas Foster Cheesecake",
    "Butterscotch Cheesecake",
    "Caramel Fudge Swirl",
    "Carrot, Green Apple & Passion Fruit",
    "Chocolate Peanut Butter",
    "Chocolate Peanut Butter Pretzel",
    "Cinnamon Turtle",
    "Apricot",
    "Balsamic",
    "Black Pepper",
    "Buttered Popcorn",
    "Cranberry",
    "Redbull",
    "Toffee",
    "Vanilla",
    "Cotton Candy",
    "Jelly Tip",
    "Masala Chai",
    "Red Velvet Cake",
    "Almond Chocolate Coconut",
    "Butterscotch, Chocolate, Toffee & Vanilla",
    "Caramel & Sea Salt",
    "Cherry Vanilla",
    "Chocolate, Fudge, Peanuts & Vanilla (aka Tin Roof)",
    "Chocolate, Strawberry & Vanilla (aka Neapolitan)",
    "Honeycomb & Vanilla (Hokey pokey)",
    "Baci",
    "Blackberry",
    "Butterscotch",
    "Corn",
    "Cucumber",
    "Mango",
    "Peppermint",
    "Pickle",
    "Devils Chocolate Cake",
    "German Chocolate Cake",
    "Apple Cinnamon",
    "Banana & Strawberry",
    "Banana Caramel",
    "Banana Caramel Pudding",
    "Coconut Pineapple",
    "Cookies & Cream",
    "Cream & Orange",
    "Jalapeno Popper",
    "Pumpkin & Vanilla",
    "Nuts",
    "Thai Tea",
    "Apple Crumble",
    "Bear Claw",
    "Chai (tea)",
    "Chocolate Custard",
    "Almond Chocolate",
    "Amaretto Brownie",
    "Caramel Cone",
    "Caramel, Cinnamon & Pralines",
    "Caramel, Sea Salt & Toffee",
    "Chocolate, Coffee & Nuts",
    "Cookies & Mint",
    "Cranberry Gingersnap",
    "Malted Milk",
    "Peanut Butter & Pickle",
    "Praline",
    "Rum",
    "Toast",
    "Vanilla Fudge",
    "Black Forest",
    "Cappuccino",
    "Carrot Cake",
    "Sour Apple",
    "Strawberry Shortbread",
    "Almond Mocha Fudge",
    "Banana Blueberry",
    "Black Raspberry Brownie",
    "Cappuccino Toffee",
    "Chocolate Chocolate Mint",
    "Chocolate Orange",
    "Chocolate, Peanuts & Fudge (aka Tin roof)",
    "Crumbly Thin Mint",
    "Sour Apple & Jolly Rancher",
    "Acai Berry",
    "Cookies",
    "Lychee",
    "Pepper",
    "Lucuma",
    "Apple & Spices",
    "Bacon & Cherry",
    "Black Cherry",
    "Black Raspberry Chocolate Chunk",
    "Butter Rum",
    "Caramel & Nuts",
    "Chocolate Chocolate (Double Chocolate)",
    "Chocolate, Strawberry & White Chocolate",
    "Cookie & Milk",
    "Cream & Pralines",
    "Dried Apricot & Pistachio",
    "Guava & Sherbet",
    "Blue Cheese",
    "Cardamom",
    "Cinnamon",
    "Guiness",
    "Hazelnut",
    "Pistachio",
    "Cadbury Marvellous Creations",
    "Key Lime Pie",
    "Oatmeal Cookie Dough",
    "Samoa",
    "Almond, Caramel & Chocolate",
    "Almond, Chocolate & Marshmallow",
    "Apple, Caramel & Cheddar",
    "Brownie Nut",
    "Caramel, Fudge, Vanilla & Waffle Cone Pieces",
    "Carrot & Orange",
    "Chocolate & Peanut Butter",
    "Chocolate Coffee",
    "Chocolate, Fudge & Raspberry",
    "Chocolate, Hazelnut & Fudge",
    "Chocolate, Nuts & Vanilla",
    "Chocolate, Peppermint & Toffee",
    "Lemon, Sweet Cream & Vanilla Wafers",
    "Lemongrass & Mint",
    "Raspberry & White Chocolate",
    "Salty Lime",
    "Caramel",
    "Carrot",
    "Ferrero Rocher",
    "Licorice (Liquorice)",
    "Peach",
    "Café Vienna",
    "Panforte",
    "Snickerdoodle",
    "Black Walnut",
    "Bumbleberry Cheesecake",
    "Butter Pecan",
    "Caramel, Fudge & Vanilla",
    "Cherry Kahlua",
    "Cotton Candy & Gummy Bears",
    "Honeycomb & Sweet Cream",
    "Jaffa Orange",
    "Peanut Butter & Toffee",
    "Blueberry",
    "Cheese",
    "Tangerine",
    "Banana Foster",
    "Brownie Batter",
    "Lucky charms",
    "Almond, Coconut & Fudge",
    "Banana Nut Fudge",
    "Cannoli, Ricotta & Pistachios",
    "Caramel, Chocolate & Pecans",
    "Cereal & Milk",
    "Chocolate Chocolate Fudge",
    "Chocolate, Chocolate & Chocolate (Triple Chocolate)",
    "Ginger Honey",
    "Graham Ribbons, Pumpkin & Vanilla Wafers",
    "Maple Bacon",
    "Peppermint & White Chocolate",
    "Bacon",
    "Barbeque",
    "Basil",
    "Honey",
    "Oreo",
    "Birthday Cake",
    "Chocolate Mudcake",
    "Margarita",
    "White Raspberry Truffle",
    "Almond Cherry",
    "Almond, Chocolate, Fudge, Walnuts & White Chocolate",
    "Amaretto Chocolate Chip Cheesecake",
    "Balsamic & Strawberry",
    "Blue Raspberry",
    "Candy Bar Pie",
    "Caramel Crunchie",
    "Cherry & White Chocolate",
    "Chocolate, Coconut & Pecan",
    "Coffee & Vanilla",
    "Maple Chestnut",
    "Lemongrass",
    "Raspberry",
    "Cheese & Corn",
    "Oreo Cheesecake",
    "Pina Colada",
    "Pumpkin Cheesecake",
    "Black Raspberry Cheesecake",
    "Cheesecake Brownie",
    "Chocolate & Strawberry",
    "Coconut, Marshmallow & Vanilla Wafers",
    "Orange & Sherbert",
    "Kiwi Fruit",
    "Vegemite",
    "Fruit Loops",
    "Irish Coffee",
    "Irish Cream",
    "Chocolate Fudge Brownie",
    "Malt & Chocolate",
    "Old Fashioned & Toffee",
    "Raspberry & Vanilla",
    "Turron",
    "Butter",
    "Cream",
    "Fig",
    "Ricotta",
    "Rose",
    "Salt",
    "Cherry Cheesecake",
    "Almond Coconut",
    "Amaretto Brownie Cheesecake",
    "Banana Coconut Macaroon Cheesecake",
    "Banana, Cream, Chocolate, Peanut Butter",
    "Butter Pecan Caramel",
    "Butterfudge, Peanut Butter & Mini Peanut Butter Cups",
    "Caramel & Macadamia",
    "Caramel, Chocolate, Cookie Dough & Vanilla",
    "Chocolate Peanut Butter Cheesecake",
    "Chocolate Pistachio Almond",
    "Coffee & Toffee",
    "Honey, Lavender & Sweet Cream",
    "Maple Walnut",
    "Orange & Vanilla",
    "Strawberry Strawberry (Double Strawberry)",
    "Almond Joy",
    "Chocolate Fudge",
    "Lamington",
    "Strawberry Shortcake",
    "Caramel & Vanilla",
    "Cherry Chocolate",
    "Chocolate Chocolate Chocolate (Triple Chocolate)",
    "Chocolate Malt",
    "Date, Rum & Pecan",
    "Fudge Vanilla",
    "Lavender honey",
    "Nutella Toffee",
    "Orange & Pineapple",
    "Pumpkin Spice",
    "Raspberry & Rum",
    "Cherry",
    "Dried Apricot",
    "Ginger",
    "Blueberry Cheesecake",
    "Cookie Monster",
    "Lemon Pie",
    "Caramel Macchiato",
    "Chocolate Kahlua",
    "Chocolate Raspberry Truffle",
    "Cinnamon Sopapia & Honey",
    "Cookies & White Chocolate",
    "Pineapple Orange",
    "Raspberry & Peach",
    "Toffee & Vanilla",
    "Jam",
    "Lavender",
    "Cherry Garcia",
    "Almond, Kahlua Fudge",
    "Caramel, Chocolate, Fudge & Marshmallow",
    "Chocolate Mint (aka After Eight)",
    "Chocolate, Malted Vanilla & Peanut Butter",
    "Coconut & Blue Curacao Liquor",
    "Coffee & Cookie",
    "English Toffee",
    "Lemon Pepper",
    "Macadamia Maple",
    "Candy Corn",
    "Crab",
    "Bourbon Cherry & Cacao Nib",
    "Butter Toffee",
    "Coconut & Cookies",
    "Fudge & Peanut Butter",
    "Berry",
    "Cantaloupe",
    "Mint",
    "Chocolate Brownie",
    "Chocolate Chip Cookie",
    "Pumpkin Latte",
    "Amaretto Cherry",
    "Caramel, Fudge & White Chocolate",
    "Chocolate Mocha",
    "Chocolate Oreo",
    "Chocolate Raspberry",
    "Chocolate, Fudge, Peanut Butter & Vanilla",
    "Espresso Fudge",
    "Graham Cracker, Mocha & Fudge",
    "Malted Strawberry",
    "Melon",
    "Sopapilla",
    "White Chocolate",
    "Boston Cream Pie",
    "Cherry Cobbler",
    "Chocolate Chip Cookie Dough",
    "Chocolate, Marshmallow & Nuts (aka Rocky Road)",
    "Cinnamon Bun",
    "Fudge Brownie",
    "S’mores",
    "Chocolate Marshmallow",
    "Chocolate Raspberry Cheesecake",
    "Chocolate Stout",
    "Pecan & Pumpkin Cheesecake",
    "Apple",
    "Honeycomb",
    "Junior Mint",
    "Ale & Honey Roasted Peanuts",
    "Almond, Banana & Chocolate Fudge",
    "Almond, Coffee & Chocolate",
    "Black Cherry Cheesecake",
    "Butterfinger, Peanut Butter & Toffee",
    "Chocolate Walnut",
    "Cream & Peanut Butter",
    "Dark Chocolate, Honey & Sea Salt",
    "Malt, Fudge, Rum & Vanilla",
    "Oatmeal Raisin",
    "Butterfinger",
    "Strawberry",
    "Apple Pie",
    "Blue Moon",
    "Peach Crumble",
    "Black Raspberry Crunch",
    "Blackberry Bramble",
    "Cherry Pecan",
    "Dulce de Leche",
    "Ginger Snap",
    "Licorice (Liquorice) & Orange",
    "Cannoli",
    "Green Tea",
    "Guava",
    "Peanut Butter",
    "Peanut Brittle",
    "Blackberry Cheesecake",
    "Bubblegum Cheesecake",
    "Chocolate, Graham Crackers & Honeycomb",
    "Dark Cherry",
    "Chilli",
    "Bastani Sonnati",
    "Christmas Pudding",
    "Almond & Marshmallow",
    "Caramel & Cookie",
    "Chocolate Hazelnut (aka Gianduja)",
    "Honey & Peaches",
    "Lime Sherbet",
    "Beer",
    "Plum",
    "Prosecco",
    "Tamarind",
    "Chocolate, Coffee & Mocha",
    "Mint Fudge",
    "Bumbleberry",
    "Cherry Cordial",
    "Candy Bar Whirl",
    "Blackberry Lavender",
    "Chocolate, Salted Caramel & Toffee",
    "Lemon",
    "Blueberry & Brown Sugar",
    "Blueberry White Chocolate",
    "Caramel & Coffee",
    "Caramel with Malted Butterfudge & Chocolate Krispies",
    "Peach, Raspberry & Vanilla",
    "Praline & Toffee",
    "Custard",
    "Pumpkin",
    "Raisin",
    "Chilli, Ginger & Lemongrass",
    "Root Beer",
    "Watermelon",
    "Cheesecake",
    "Almond Butter",
    "Chocolate Mint Cookie",
    "Coconut & Dark Chocolate",
    "Coffee & English Toffee",
    "Lemon Custard",
    "Brown Bread & Grape-Nuts Breakfast Cereal",
    "Kaffir Lime",
    "Butterfinger Cheesecake",
    "Chocolate",
    "Milo",
    "Turkish Delight",
    "Berry & Rhubarb",
    "Fudge, Peanuts & Vanilla",
    "Macadamia",
    "Bubblegum",
    "Banana Chocolate",
    "Brown Sugar & Cinnamon",
    "Caramel Caramel (Double Caramel)",
    "Grape Nut",
    "Peanut Butter Cheesecake",
    "Cherry Sherbet & Vanilla",
    "Brownie, Chocolate & Chocolate Krispies",
    "Malt & Vanilla",
    "Almond & Blueberry",
    "Aachener Printen",
    "Abernethy",
    "Acıbadem kurabiyesi",
    "Afghan biscuits",
    "Alfajor",
    "Almond biscuit",
    "Almond cake, almond cookie",
    "Amaretti di Saronno",
    "Animal cracker",
    "ANZAC biscuit",
    "Aparon",
    "Apas",
    "Apple cider cookie",
    "Baci di dama",
    "Ballokume (from Turkish bal-lokum)",
    "Barquillo",
    "Barquiron",
    "Basler Läckerli",
    "Bath Oliver",
    "Berger Cookie",
    "Berner Haselnusslebkuchen",
    "Berner Honiglebkuchen",
    "biscochito",
    "Biscocho",
    "Biscotti",
    "Biscuit",
    "Biscuit roll",
    "Bizcochito",
    "Black and white cookie",
    "boorsoq, or bawyrsak",
    "Boortsog",
    "Bourbon biscuit",
    "Bourbon cream or Bourbon",
    "Bredela",
    "Bredele, Bredle or Winachtsbredele",
    "Broas",
    "Butter cookie",
    "Butter pecan",
    "Camachile cookie",
    "Caramel shortbread",
    "Carrot cake cookie",
    "Cat's tongue cookie",
    "Cavallucci",
    "Caycay",
    "Charcoal biscuit",
    "Chinese walnut cookie",
    "Chocolate biscuit",
    "Chocolate chip cookie",
    "Chocolate Teacake",
    "Chocolate-coated marshmallow treats",
    "Christmas cookies",
    "Coconut macaroon",
    "Cornish fairings",
    "Cowboy cookies",
    "Coyotas",
    "Cream cracker",
    "Cuccidati",
    "Cuchuflís or Cubanitos",
    "Custard cream",
    "Digestive biscuit",
    "Drabbelkoek",
    "Dutch letter",
    "egg roll (鸡蛋卷), love letters, kueh belandah, crispy biscuit roll, crisp biscuit roll or cookie roll",
    "Empire biscuit",
    "Fig bar / Fig roll",
    "Finskepinner",
    "Florentine Biscuit",
    "Flour kurabiye (Un kurabiyesi)",
    "Fortune cookie",
    "Fudge cookie",
    "Galletas de bato (Rosquillos)",
    "Galletas de patatas",
    "Galletas del Carmen",
    "Galletas pesquera",
    "Garibaldi biscuit",
    "Gazelle ankles",
    "Ghorabiye",
    "Ghoriba",
    "Ginger snaps",
    "Gingerbread",
    "Gingerbread man",
    "Half-Moon cookie",
    "Half-moon cookie",
    "Hamantash",
    "Jacobina",
    "Jammie Dodgers",
    "Janhagel",
    "Jodenkoek",
    "Joe Frogger",
    "Jumble",
    "Kaasstengels",
    "Kahk",
    "Khapse",
    "Kiâm-piánn",
    "Kichel",
    "Kleicha",
    "Koulourakia",
    "Kourabiedes",
    "Krumiri",
    "Krumkake",
    "Kue gapit",
    "Kue satu",
    "Lady Finger (cookie)",
    "Lebkuchen",
    "Leckerli, Läggerli",
    "Lengua de gato",
    "Lincoln biscuit",
    "Linga",
    "Linzer cookie",
    "Ma'amoul",
    "Macaron",
    "Macaroon",
    "Malted milk (biscuit)",
    "Mamón tostado",
    "Mandelbrot",
    "Maple leaf cream cookies",
    "Marie biscuit",
    "Masa podrida",
    "Millionaire's Shortbread",
    "Moravian spice cookies",
    "Nice biscuit",
    "Nocciolini di Canzo",
    "Oat crisps",
    "Oatmeal raisin",
    "Otap",
    "Paborita",
    "Paciencia",
    "Panellets",
    "Paprenjak",
    "Party ring",
    "Peanut butter cookie",
    "Pepernoten",
    "Petit-Beurre",
    "Picnic biscuit",
    "Pignolo (macaroon)",
    "Piñata cookie",
    "Pineapple tart",
    "Pizzelle",
    "Polvorón",
    "Puto seco",
    "Putri salju",
    "Rainbow cookie",
    "Reshteh Khoshkar",
    "Ricciarelli",
    "Rich tea",
    "Rosca or biscocho de rosca",
    "Rosette",
    "Rosquillo",
    "Rum ball",
    "Russian tea cake",
    "Sandwich cookie",
    "Semprong",
    "Shortbread",
    "Silvana",
    "Sindhi mithi mani",
    "Snickerdoodle",
    "Speculaas",
    "Springerle",
    "Spritzgebäck",
    "Square cookie",
    "Stroopwafel",
    "Sugar cookie",
    "Tahini cookie",
    "Tareco",
    "Teiglach",
    "Tirggel",
    "Toruń gingerbread",
    "Ube crinkles",
    "Ugoy-ugoy",
    "Uraró",
    "Vanillekipferl",
    "Wafer",
    "Wibele",
]